import { DriveDirectSectionHeaderModel } from "./driveDirectData"

/* FAQ Data */
export type DriveDirectFaqData = {
    header: DriveDirectSectionHeaderModel,
    faqs: DriveDirectFaqItem[]
}

export type DriveDirectFaqItem = {
    question: string,
    answer: string
}

export const driveDirectFaqData: DriveDirectFaqData = {
    header: {
        badge: "FAQs",
        title: "Got Questions?",
        desc: "Answers to common questions about using the Google Drive Direct Link Generator."
    },
    faqs: [
        {
            question: "Is Drive Direct a Google Drive direct link converter?",
            answer: "Yes, Drive Direct works as a Google Drive share link to direct download link converter. Paste any Google Drive shareable link and it instantly converts it into a direct download URL."
        },
        {
            question: "Is Drive Direct free to use?",
            answer: "Yes, Drive Direct is completely free to use with no hidden charges or fees."
        },
        {
            question: "Do I need to log in to use Drive Direct?",
            answer: "No, Drive Direct does not require any login or account creation."
        },
        {
            question: "Is my data secure with Drive Direct?",
            answer: "Yes, Drive Direct works offline within your browser, ensuring your data is not uploaded to any servers."
        },
        {
            question: "Is there a limit to how many links I can generate?",
            answer: "No, you can generate as many direct download links as you need without any restrictions."
        },
        {
            question: "Can I generate multiple direct download links at once?",
            answer: "Yes, Drive Direct supports generating multiple direct download links in one go. From the hero section select the 'Multiple' tab to generate links for multiple Google Drive URLs."
        },
        {
            question: "What types of files can I generate direct download links for?",
            answer: "You can generate direct download links for any file type stored in Google Drive, including documents, images, videos, and more."
        },
        {
            question: "Will the direct download links expire?",
            answer: "No, the direct download links generated by Drive Direct do not expire and can be used anytime."
        },
        {
            question: "Is there any limitations on file size?",
            answer: "Yes, there is a limitation based on Google Drive's own sharing policies. Generally, for larger files Google Drive opens a web page."
        },
        {
            question: "Can I use the generated direct download links for embedding in websites or sharing with others?",
            answer: "Yes, but not recommended. Basically it is not a replacement for a CDN. You can use it for simple use case such as demos, prototyping or temporary assets. The direct download links generated by Drive Direct can be used for downloading in websites, sharing via email, or using in automation workflows."
        },
        {
            question: "Can a direct link bypass Google Drive's download limit?",
            answer: "No. A direct link skips Google Drive's file preview and virus-scan warning page, but it cannot bypass Google's own quota. If a file hits Google's 'too many users have viewed or downloaded this file' limit, every link to it, direct or shared, will be blocked until Google resets the quota. Splitting a file across a copy or waiting it out are the only real workarounds."
        }
    ]
}